apiVersion: sailoperator.io/v1
kind: Istio
metadata:
  name: default
spec:
  namespace: {{ .Values.servicemesh.namespace }}
  version: {{ .Values.servicemesh.ossm3version }}
  values:
    meshConfig:
{{ toYaml .Values.servicemesh.ossm3meshconfig | indent 6 }}