apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    app: prometheus-istiod-monitor
  name: sm-istiod
  namespace: {{ .Values.servicemesh.namespace }}
spec:
  targetLabels:
  - app
  endpoints:
  - interval: {{ .Values.servicemeshMonitoring.scrapeInterval }}}
      port: {{ .Values.servicemeshMonitoring.scrapePort }}
      relabelings:
      - action: replace
        replacement: {{ .Values.servicemesh.mesh_id }}
        targetLabel: mesh_id
  selector:
    matchLabels:
      app: {{ .Values.servicemeshMonitoring.labelSelector }}

    