apiVersion: telemetry.istio.io/v1alpha1
kind: Telemetry
metadata:
  name: enable-prometheus-metrics
  namespace: {{ .Values.servicemesh.namespace }}
spec:
  metrics:
    - providers:
        - name: prometheus